name: Build index

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: honeycombio/gha-buildevents@v2
        with:
          # Required: a Honeycomb API key - needed to send traces.
          apikey: ${{ secrets.BUILDEVENT_APIKEY }}
          # Required: the Honeycomb dataset to send traces to.
          dataset: gha-buildevents_integration
          # Required on the final job: status, this will be used in the post section and sent
          # as status of the trace.
          # Note: in V1 this was called job-status which has been deprecated
          status: ${{ job.status }}

      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: |-
          STEP_ID=setup-go
          STEP_START=$(date +%s)

          go version

          buildevents step $TRACE_ID $STEP_ID $STEP_START $STEP_ID
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.118.2'
          extended: true

      - name: Build index
        run: |-
          STEP_ID=build-hugo
          STEP_START=$(date +%s)

          hugo

          buildevents step $TRACE_ID $STEP_ID $STEP_START $STEP_ID
      - name: Upload index
        env:
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        run: |-
          STEP_ID=upload-index
          STEP_START=$(date +%s)

          go mod download
          go run algolia.go

          buildevents step $TRACE_ID $STEP_ID $STEP_START $STEP_ID
