name: Build index

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: honeycombio/gha-buildevents@v2
        with:
          # Required: a Honeycomb API key - needed to send traces.
          apikey: ${{ secrets.BUILDEVENT_APIKEY }}
          # Required: the Honeycomb dataset to send traces to.
          dataset: gha-buildevents_integration
          # Required on the final job: status, this will be used in the post section and sent
          # as status of the trace.
          # Note: in V1 this was called job-status which has been deprecated
          status: ${{ job.status }}

      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.15.3"
      - run: buildevents cmd $TRACE_ID $STEP_ID go version

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.118.2'
          extended: true

      - name: Build index
        run: buildevents cmd $TRACE_ID $STEP_ID hugo

      - name: Upload index
        env:
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        run: |-
          buildevents cmd $TRACE_ID $STEP_ID go mod download
          buildevents cmd $TRACE_ID $STEP_ID go run algolia.go
